/**
 * Make the embedded cover fonts visible to librsvg.
 *
 * sharp rasterizes the cover's SVG overlay through libvips → librsvg, and
 * **librsvg ignores `@font-face` webfonts entirely** — it resolves families
 * through fontconfig only. Embedding the woff2 as a base64 `src:url(...)` in
 * the SVG (which this project did until now) is silently inert: text renders
 * in whatever fallback fontconfig picks. Verified by rendering the same string
 * with the face embedded, without it, and under a deliberately nonexistent
 * family name — all three produce byte-identical output.
 *
 * So the fonts have to reach fontconfig as real files on a scanned path. Rather
 * than installing them into /usr/share/fonts (which only fixes the container
 * and leaves dev, CI and the benchmark rendering differently), this generates a
 * fontconfig file pointing at assets/fonts and exports it via FONTCONFIG_FILE.
 * One code path, identical rendering everywhere.
 *
 * **Ordering matters.** fontconfig reads its configuration once, at first use,
 * and caches it: setting FONTCONFIG_FILE after something has already rendered
 * text is silently ignored. Setting it at module-evaluation time is safe —
 * every module is evaluated long before the first cover is built — which is why
 * this runs as an import side effect rather than being called from a builder.
 */
import { mkdtempSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONT_FACES } from './fonts.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** assets/fonts relative to this module (src|dist /cover -> ../../assets/fonts). */
export const COVER_FONTS_DIR = join(__dirname, '..', '..', 'assets', 'fonts');

const escapeXml = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Build the fontconfig XML: scan `fontsDir`, and alias each design-facing
 * family onto the name its file actually self-reports where the two differ.
 *
 * Pure and exported so the generated rules can be asserted without touching
 * the filesystem or the environment.
 */
export function buildFontConfig(fontsDir: string, cacheDir: string): string {
  // All three Bricolage weights share one alias, so key the dedup on the pair
  // rather than emitting a duplicate rule per face. Family names contain
  // spaces, so the key is joined with a character that cannot appear in one.
  const pairs = new Map<string, [string, string]>();
  for (const f of FONT_FACES) {
    if (f.fcFamily) pairs.set(`${f.family}|${f.fcFamily}`, [f.family, f.fcFamily]);
  }

  const aliases = [...pairs.values()]
    .map(
      ([family, fcFamily]) => `  <match target="pattern">
    <test name="family"><string>${escapeXml(family)}</string></test>
    <edit name="family" mode="assign" binding="same"><string>${escapeXml(fcFamily)}</string></edit>
  </match>`,
    )
    .join('\n');

  return `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by src/cover/fontconfig.ts. Do not edit; edit FONT_FACES. -->
<fontconfig>
  <include ignore_missing="yes">/etc/fonts/fonts.conf</include>
  <dir>${escapeXml(fontsDir)}</dir>
  <cachedir>${escapeXml(cacheDir)}</cachedir>
${aliases}
</fontconfig>
`;
}

let configured = false;

/**
 * Write the generated config and point fontconfig at it. Idempotent, and a
 * no-op if FONTCONFIG_FILE is already set so an operator can override it.
 * Returns the config path in use, or undefined if the fonts are not present
 * (tests and callers that never rasterize a cover should not be forced to
 * have them).
 */
export function ensureFontConfig(fontsDir: string = COVER_FONTS_DIR): string | undefined {
  if (configured) return process.env.FONTCONFIG_FILE;
  configured = true;
  if (process.env.FONTCONFIG_FILE) return process.env.FONTCONFIG_FILE;
  if (!existsSync(fontsDir)) return undefined;

  const dir = mkdtempSync(join(tmpdir(), 'kindle-digest-fc-'));
  const cacheDir = join(dir, 'cache');
  mkdirSync(cacheDir, { recursive: true });
  const conf = join(dir, 'fonts.conf');
  writeFileSync(conf, buildFontConfig(fontsDir, cacheDir));
  process.env.FONTCONFIG_FILE = conf;
  return conf;
}

ensureFontConfig();
